### ISSUE TITLE
Please add NeurIPS 2019

### ISSUE THREAD

**Issue by negrinho** [hibayesian/awesome-automl-papers#25]
Towards modular and programmable architecture search
Paper: https://arxiv.org/abs/1909.13404
Code: https://github.com/negrinho/deep_architect
Documentation: https://deep-architect.readthedocs.io/en/latest/

Techically, this is still DeepArchitect (but the old repo was renamed and now its [here](https://github.com/negrinho/deep_architect_legacy)). This work extends the ideas in the [original paper](https://arxiv.org/abs/1704.08792). The implementation is much more mature and supports arbitrary deep learning frameworks. We will maintain it and extend it going forward.

Thank you

**Comment by Alro10** [comment]
Hi! @negrinho 

I added your paper and opened a PR. Your work looks amazing!

Thanks.

**Comment by negrinho** [comment]
Thanks! Here is a link to a [Colab link](https://colab.research.google.com/drive/14xZdGB-BbIivdgNje3Gu7ZmK0m4F02kE#scrollTo=OKv4Iq4F2mBY) too in case you want to try it.
